apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-blazor
  namespace: dotnet-blazor
  labels:
    app: dotnet-blazor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-blazor
  template:
    metadata:
      labels:
        app: dotnet-blazor
    spec:
      containers:
      - name: dotnet-blazor
        image: dotnet-blazor
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "768Mi"
            cpu: "500m"
      restartPolicy: Always
