apiVersion: v1
kind: Service
metadata:
  name: dotnet-blazor
  namespace: dotnet-blazor
  labels:
    app: dotnet-blazor
spec:
  type: ClusterIP
  selector:
    app: dotnet-blazor
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
